name: Build

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v6

      - run: |
          mkdir files
          cp $ANDROID_HOME/platforms/android-37.0/package.xml files/gha-package.xml
          ls $ANDROID_HOME/platforms
          rm -rf $ANDROID_HOME/paltforms
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager 'platforms;android-37.0'
          ./gradlew assembleRegularRelease || true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package.xml
          path: files/
