name: Build

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v6
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - run: |
          mkdir files
          mv $ANDROID_HOME/platforms/android-37.0/package.xml files
          rm -rf $ANDROID_HOME/platforms
          pip install requests looseversion
          curl -Lo sdkmanager.py https://gitlab.com/fdroid/sdkmanager/-/raw/master/sdkmanager.py
          python3 sdkmanager.py 'platforms;android-37.0'
          ./gradlew assembleRegularRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package.xml
          path: files/
