name: Build

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v6

      - run: |
          mv $ANDROID_HOME/platforms/android-37.0 android-37.0
          ./gradlew assembleRegularRelease || true
          diff -r $ANDROID_HOME/platforms/android-37.0 android-37.0
          rm $ANDROID_HOME/platforms/android-37.0/package.xml
          cp android-37.0/package.xml $ANDROID_HOME/platforms/android-37.0
          ./gradlew assembleRegularRelease
